"""Shared utility functions and constants for the IPCC Literature app."""

from typing import Any

# ---- Constants ----
MAX_RESULTS_LIMIT: int = 5000
DISPLAY_CONTAINER_HEIGHT: int = 420
OPENALEX_PAGE_SIZE: int = 200
MAX_WORK_TYPES: int = 3
DEFAULT_YEAR_START: int = 2000
DEFAULT_YEAR_END: int = 2026
YEAR_SLIDER_MIN: int = 1900
YEAR_SLIDER_MAX: int = 2027

UN_MEMBER_STATE_COUNTRY_CODE_PAIRS: list[tuple[str, str]] = [
    ("Afghanistan", "af"),
    ("Albania", "al"),
    ("Algeria", "dz"),
    ("Andorra", "ad"),
    ("Angola", "ao"),
    ("Antigua and Barbuda", "ag"),
    ("Argentina", "ar"),
    ("Armenia", "am"),
    ("Australia", "au"),
    ("Austria", "at"),
    ("Azerbaijan", "az"),
    ("Bahamas (The)", "bs"),
    ("Bahrain", "bh"),
    ("Bangladesh", "bd"),
    ("Barbados", "bb"),
    ("Belarus", "by"),
    ("Belgium", "be"),
    ("Belize", "bz"),
    ("Benin", "bj"),
    ("Bhutan", "bt"),
    ("Bolivia (Plurinational State of)", "bo"),
    ("Bosnia and Herzegovina", "ba"),
    ("Botswana", "bw"),
    ("Brazil", "br"),
    ("Brunei Darussalam", "bn"),
    ("Bulgaria", "bg"),
    ("Burkina Faso", "bf"),
    ("Burundi", "bi"),
    ("Cabo Verde", "cv"),
    ("Cambodia", "kh"),
    ("Cameroon", "cm"),
    ("Canada", "ca"),
    ("Central African Republic", "cf"),
    ("Chad", "td"),
    ("Chile", "cl"),
    ("China (the People's Republic of)", "cn"),
    ("Colombia", "co"),
    ("Comoros", "km"),
    ("Congo", "cg"),
    ("Costa Rica", "cr"),
    ("Côte D'Ivoire", "ci"),
    ("Croatia", "hr"),
    ("Cuba", "cu"),
    ("Cyprus", "cy"),
    ("Czechia", "cz"),
    ("Democratic People's Republic of Korea", "kp"),
    ("Democratic Republic of the Congo", "cd"),
    ("Denmark", "dk"),
    ("Djibouti", "dj"),
    ("Dominica", "dm"),
    ("Dominican Republic", "do"),
    ("Ecuador", "ec"),
    ("Egypt", "eg"),
    ("El Salvador", "sv"),
    ("Equatorial Guinea", "gq"),
    ("Eritrea", "er"),
    ("Estonia", "ee"),
    ("Eswatini", "sz"),
    ("Ethiopia", "et"),
    ("Fiji", "fj"),
    ("Finland", "fi"),
    ("France", "fr"),
    ("Gabon", "ga"),
    ("Gambia (Republic of The)", "gm"),
    ("Georgia", "ge"),
    ("Germany", "de"),
    ("Ghana", "gh"),
    ("Greece", "gr"),
    ("Grenada", "gd"),
    ("Guatemala", "gt"),
    ("Guinea", "gn"),
    ("Guinea Bissau", "gw"),
    ("Guyana", "gy"),
    ("Haiti", "ht"),
    ("Honduras", "hn"),
    ("Hungary", "hu"),
    ("Iceland", "is"),
    ("India", "in"),
    ("Indonesia", "id"),
    ("Iran (Islamic Republic of)", "ir"),
    ("Iraq", "iq"),
    ("Ireland", "ie"),
    ("Israel", "il"),
    ("Italy", "it"),
    ("Jamaica", "jm"),
    ("Japan", "jp"),
    ("Jordan", "jo"),
    ("Kazakhstan", "kz"),
    ("Kenya", "ke"),
    ("Kiribati", "ki"),
    ("Kuwait", "kw"),
    ("Kyrgyzstan", "kg"),
    ("Lao People’s Democratic Republic", "la"),
    ("Latvia", "lv"),
    ("Lebanon", "lb"),
    ("Lesotho", "ls"),
    ("Liberia", "lr"),
    ("Libya", "ly"),
    ("Liechtenstein", "li"),
    ("Lithuania", "lt"),
    ("Luxembourg", "lu"),
    ("Madagascar", "mg"),
    ("Malawi", "mw"),
    ("Malaysia", "my"),
    ("Maldives", "mv"),
    ("Mali", "ml"),
    ("Malta", "mt"),
    ("Marshall Islands", "mh"),
    ("Mauritania", "mr"),
    ("Mauritius", "mu"),
    ("Mexico", "mx"),
    ("Micronesia (Federated States of)", "fm"),
    ("Monaco", "mc"),
    ("Mongolia", "mn"),
    ("Montenegro", "me"),
    ("Morocco", "ma"),
    ("Mozambique", "mz"),
    ("Myanmar", "mm"),
    ("Namibia", "na"),
    ("Nauru", "nr"),
    ("Nepal", "np"),
    ("Netherlands (Kingdom of the)", "nl"),
    ("New Zealand", "nz"),
    ("Nicaragua", "ni"),
    ("Niger", "ne"),
    ("Nigeria", "ng"),
    ("North Macedonia", "mk"),
    ("Norway", "no"),
    ("Oman", "om"),
    ("Pakistan", "pk"),
    ("Palau", "pw"),
    ("Panama", "pa"),
    ("Papua New Guinea", "pg"),
    ("Paraguay", "py"),
    ("Peru", "pe"),
    ("Philippines", "ph"),
    ("Poland", "pl"),
    ("Portugal", "pt"),
    ("Qatar", "qa"),
    ("Republic of Korea", "kr"),
    ("Republic of Moldova", "md"),
    ("Romania", "ro"),
    ("Russian Federation", "ru"),
    ("Rwanda", "rw"),
    ("Saint Kitts and Nevis", "kn"),
    ("Saint Lucia", "lc"),
    ("Saint Vincent and the Grenadines", "vc"),
    ("Samoa", "ws"),
    ("San Marino", "sm"),
    ("Sao Tome and Principe", "st"),
    ("Saudi Arabia", "sa"),
    ("Senegal", "sn"),
    ("Serbia", "rs"),
    ("Seychelles", "sc"),
    ("Sierra Leone", "sl"),
    ("Singapore", "sg"),
    ("Slovakia", "sk"),
    ("Slovenia", "si"),
    ("Solomon Islands", "sb"),
    ("Somalia", "so"),
    ("South Africa", "za"),
    ("South Sudan", "ss"),
    ("Spain", "es"),
    ("Sri Lanka", "lk"),
    ("Sudan", "sd"),
    ("Suriname", "sr"),
    ("Sweden", "se"),
    ("Switzerland", "ch"),
    ("Syrian Arab Republic", "sy"),
    ("Tajikistan", "tj"),
    ("Thailand", "th"),
    ("Timor-Leste", "tl"),
    ("Togo", "tg"),
    ("Tonga", "to"),
    ("Trinidad and Tobago", "tt"),
    ("Tunisia", "tn"),
    ("Türkiye", "tr"),
    ("Turkmenistan", "tm"),
    ("Tuvalu", "tv"),
    ("Uganda", "ug"),
    ("Ukraine", "ua"),
    ("United Arab Emirates", "ae"),
    ("United Kingdom of Great Britain and Northern Ireland", "gb"),
    ("United Republic of Tanzania", "tz"),
    ("United States of America", "us"),
    ("Uruguay", "uy"),
    ("Uzbekistan", "uz"),
    ("Vanuatu", "vu"),
    ("Venezuela, Bolivarian Republic of", "ve"),
    ("Viet Nam", "vn"),
    ("Yemen", "ye"),
    ("Zambia", "zm"),
    ("Zimbabwe", "zw"),
]

UN_MEMBER_STATES: list[str] = [name for name, _ in UN_MEMBER_STATE_COUNTRY_CODE_PAIRS]
UN_MEMBER_STATE_TO_COUNTRY_CODE: dict[str, str] = dict(UN_MEMBER_STATE_COUNTRY_CODE_PAIRS)


def record_identifier(rec: dict[str, Any] | None) -> str:
    """Generate a unique identifier for a publication record.

    Uses OpenAlex URL if available, otherwise falls back to title.
    Both are normalized to lowercase for case-insensitive matching.

    Parameters
    ----------
    rec : dict or None
        A publication record dictionary with optional "OpenAlex URL" and "Title" keys.

    Returns
    -------
    str
        A prefixed identifier string (e.g., "url::..." or "title::...").
    """
    rec_url = str((rec or {}).get("OpenAlex URL") or "").strip().lower()
    if rec_url:
        return f"url::{rec_url}"
    rec_title = str((rec or {}).get("Title") or "").strip().lower()
    return f"title::{rec_title}"
